name: Deploy expo updates

on:
  # Trigger: on new tag push
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  build:
    name: Publish changes

    runs-on: ubuntu-latest

    steps:
      # Get the repo files from current commit
      - name: Cloning repository
        uses: actions/checkout@v1

      - name: installing node 13
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install node dependencies
        run: |
          echo "Node version;"
          node --version
          npm i

      # - name: Run tests
      #   run: npm test

      # # Building app docs: https://docs.expo.io/versions/latest/distribution/building-standalone-apps/
      # # Read that guide first
      # - name: Build app binaries
      #   run: |
      #     expo build:android
      #     expo build:ios


      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}
      - name: Publish
        run: |
          npm i
          expo publish